### ISSUE TITLE
trying to use the viewer unsuccessfully: ImportError: No module named utils_unicog.viewer

### ISSUE THREAD

**Issue by chrplr** [neurospin/unicog#7]
Hello,

Working on my laptop, I first installed brainvisa, then run bv_env.sh.

######

Then I installed unicogfmri  without problem it seems:

cp983411@is153352:~/code/unicog$ python setup.py install --user
/volatile/brainvisa-4.5.0/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'distname'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
writing unicog.egg-info/PKG-INFO
writing top-level names to unicog.egg-info/top_level.txt
writing dependency_links to unicog.egg-info/dependency_links.txt
reading manifest file 'unicog.egg-info/SOURCES.txt'
writing manifest file 'unicog.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/unicogfmri
copying unicogfmri/__init__.py -> build/lib.linux-x86_64-2.7/unicogfmri
creating build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri
copying unicogfmri/utils_unicogfmri/__init__.py -> build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri
creating build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/import_data
copying unicogfmri/utils_unicogfmri/import_data/__init__.py -> build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/import_data
copying unicogfmri/utils_unicogfmri/import_data/import_and_convert_dicom.py -> build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/import_data
creating build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/viewer
copying unicogfmri/utils_unicogfmri/viewer/__init__.py -> build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/viewer
copying unicogfmri/utils_unicogfmri/viewer/pyanatomist_viewer.py -> build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/viewer
copying unicogfmri/utils_unicogfmri/viewer/pyanatomist_viewer_3D.py -> build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/viewer
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/unicogfmri
creating build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri
copying build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/__init__.py -> build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri
creating build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/import_data
copying build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/import_data/__init__.py -> build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/import_data
copying build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/import_data/import_and_convert_dicom.py -> build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/import_data
creating build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/viewer
copying build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/viewer/__init__.py -> build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/viewer
copying build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/viewer/pyanatomist_viewer.py -> build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/viewer
copying build/lib.linux-x86_64-2.7/unicogfmri/utils_unicogfmri/viewer/pyanatomist_viewer_3D.py -> build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/viewer
copying build/lib.linux-x86_64-2.7/unicogfmri/__init__.py -> build/bdist.linux-x86_64/egg/unicogfmri
byte-compiling build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/import_data/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/import_data/import_and_convert_dicom.py to import_and_convert_dicom.pyc
byte-compiling build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/viewer/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/viewer/pyanatomist_viewer.py to pyanatomist_viewer.pyc
byte-compiling build/bdist.linux-x86_64/egg/unicogfmri/utils_unicogfmri/viewer/pyanatomist_viewer_3D.py to pyanatomist_viewer_3D.pyc
byte-compiling build/bdist.linux-x86_64/egg/unicogfmri/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying unicog.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying unicog.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying unicog.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying unicog.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying unicog.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/unicog-0.1-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing unicog-0.1-py2.7.egg
removing '/home/cp983411/.local/lib/python2.7/site-packages/unicog-0.1-py2.7.egg' (and everything under it)
creating /home/cp983411/.local/lib/python2.7/site-packages/unicog-0.1-py2.7.egg
Extracting unicog-0.1-py2.7.egg to /home/cp983411/.local/lib/python2.7/site-packages
unicog 0.1 is already the active version in easy-install.pth
/home/cp983411/.local/lib/python2.7/site-packages/unicog-0.1-py2.7.egg
Processing dependencies for unicog==0.1
Finished processing dependencies for unicog==0.1

########################

I can import unicogfmri in python without problem: 

cp983411@is153352:~/code/unicog/unicogfmri/utils_unicogfmri/viewer/tests$ python
Python 2.7.3 (default, Feb 27 2014, 19:58:35) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import unicogfmri
>>>

#######

But when trying to run a modified version of the view-contrasts.py scripts:

cp983411@is153352:~/code/unicog/unicogfmri/utils_unicogfmri/viewer/tests$ python view_contrasts-mirror-patterns.py 

Traceback (most recent call last):
  File "view_contrasts-mirror-patterns.py", line 27, in <module>
    from unicogfmri.utils_unicog.viewer import pyanatomist_viewer
ImportError: No module named utils_unicog.viewer

**Comment by chrplr** [comment]
Problem solved. The import in view_contrasts.py is incorrect.

It should be: 
  from unicogfmri.utils_unicogfmri.viewer

**Comment by chrplr** [comment]
Ah. But now it crashes with 

Anatomist started.
/i2bm/local/spm8/canonical/single_subj_T1.nii : No such file or directory
Could not read object in file /i2bm/local/spm8/canonical/single_subj_T1.nii !
Traceback (most recent call last):
  File "view_contrasts-mirror-patterns.py", line 44, in <module>
    pyanatomist_viewer.fusion2D_map_activation(dic_maps)
  File "/home/cp983411/.local/lib/python2.7/site-packages/unicog-0.1-py2.7.egg/unicogfmri/utils_unicogfmri/viewer/pyanatomist_viewer.py", line 65, in fusion2D_map_activation
    template.loadReferentialFromHeader()
  File "/volatile/brainvisa-4.5.0/python/anatomist/base.py", line 1468, in loadReferentialFromHeader
    self.anatomistinstance.loadReferentialFromHeader([self])
  File "/volatile/brainvisa-4.5.0/python/anatomist/base.py", line 793, in loadReferentialFromHeader
    self.execute("LoadReferentialFromHeader", objects=self.makeList(objects) )
  File "/volatile/brainvisa-4.5.0/python/anatomist/direct/api.py", line 1020, in execute
    params=dict( (ununderscore(k),self.convertParamsToIDs(v)) for k, v in kwargs.iteritems() if v is not None )
  File "/volatile/brainvisa-4.5.0/python/anatomist/direct/api.py", line 1020, in <genexpr>
    params=dict( (ununderscore(k),self.convertParamsToIDs(v)) for k, v in kwargs.iteritems() if v is not None )
  File "/volatile/brainvisa-4.5.0/python/anatomist/base.py", line 1196, in convertParamsToIDs
    return [self.convertSingleObjectParamsToIDs(i) for i in params]
  File "/volatile/brainvisa-4.5.0/python/anatomist/direct/api.py", line 1048, in convertSingleObjectParamsToIDs
    raise TypeError( 'Expecting an Anatomist object but got one of type %s' % repr( type( v ) )  )

The module supposes that  /i2bm/local/spm8/canonical/single_subj_T1.nii
Hard to make it work on a laptop.
I see that there is a view_contrasts_specific_anat.py script. Will try it.

I followed the instructions in the doc (readme.md) to modify the view_contrasts.py.
The doc must be improved.

**Comment by chrplr** [comment]
Just discovered this in the comments of  iew_contrasts.py

"In order to change the template, use the template_file option in fusion2D_map_activation"

Should be near the call of the function.
